/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список дней в окне записи с признаком наличия свободных слотов
         * @description Используется фронтендом для подсветки дней в календаре. Возвращает только дни в пределах скользящего окна `[now, now + 14 дней]`. Дни, которые уже прошли, не возвращаются.
         */
        get: operations["getAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список слотов на конкретный день
         * @description Возвращает слоты (по 30 минут) на указанную дату со статусами `free`/`booked`. Если дата вне окна записи `[now, now + 14 дней]` — возвращается пустой список.
         */
        get: operations["getSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Записаться на выбранный свободный слот
         * @description Атомарно бронирует слот: успешным (`201`) может быть только один параллельный запрос на один и тот же слот, остальные получают `409`.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список опубликованных владельцем интервалов доступности
         * @description Без авторизации, согласно ТЗ. Используется экраном владельца для просмотра уже опубликованных интервалов.
         */
        get: operations["listOwnerAvailability"];
        put?: never;
        /**
         * Опубликовать доступный интервал (рабочие часы на день)
         * @description Из интервала система нарезает слоты по 30 минут. Интервал должен укладываться в окно записи `[now, now + 14 дней]`, иначе — `400`. Пересекающиеся с уже опубликованными интервалы — `409`.
         */
        post: operations["createOwnerAvailability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SlotStatus: "free" | "booked";
        Slot: {
            /** @example slot_20260901_0930 */
            id: string;
            /**
             * Format: date-time
             * @description Начало слота в UTC (ISO 8601)
             * @example 2026-09-01T09:30:00Z
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Конец слота в UTC (ISO 8601), всегда startAt + 30 минут
             * @example 2026-09-01T10:00:00Z
             */
            endAt: string;
            status: components["schemas"]["SlotStatus"];
        };
        AvailabilityDay: {
            /** Format: date */
            date: string;
            hasFreeSlots: boolean;
            freeSlotsCount: number;
            totalSlotsCount: number;
        };
        AvailabilityInterval: {
            /** @example avail_20260901_0900_1300 */
            id: string;
            /**
             * Format: date
             * @description Дата, на которую опубликован интервал (UTC)
             */
            date: string;
            /**
             * @description Время начала интервала в формате HH:MM (UTC)
             * @example 09:00
             */
            startTime: string;
            /**
             * @description Время конца интервала в формате HH:MM (UTC)
             * @example 13:00
             */
            endTime: string;
        };
        CreateAvailabilityIntervalRequest: {
            /** Format: date */
            date: string;
            /** @example 09:00 */
            startTime: string;
            /** @example 13:00 */
            endTime: string;
        };
        CreateBookingRequest: {
            slotId: string;
            guestName: string;
            /**
             * @description Номер телефона гостя в любом читаемом формате
             * @example +79990001122
             */
            guestPhone: string;
        };
        Booking: {
            id: string;
            slotId: string;
            guestName: string;
            guestPhone: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        Error: {
            /**
             * @description Машиночитаемый код ошибки
             * @example slot_already_booked
             */
            error: string;
            /** @example Слот уже забронирован */
            message: string;
        };
    };
    responses: {
        /** @description Некорректные параметры запроса */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAvailability: {
        parameters: {
            query?: {
                /** @description Начало диапазона (YYYY-MM-DD). По умолчанию — текущая дата (UTC). Не может быть раньше текущей даты. */
                from?: string;
                /** @description Конец диапазона (YYYY-MM-DD). По умолчанию — текущая дата + 14 дней. Не может выходить за пределы окна записи. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список дней с агрегированной информацией по слотам */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date */
                        from?: string;
                        /** Format: date */
                        to?: string;
                        days?: components["schemas"]["AvailabilityDay"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getSlots: {
        parameters: {
            query: {
                /** @description Дата в формате YYYY-MM-DD (UTC) */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список слотов на день */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date */
                        date?: string;
                        slots?: components["schemas"]["Slot"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Слот успешно забронирован */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Слот с указанным slotId не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Слот уже забронирован, либо находится вне текущего окна записи (окно пересчитывается динамически, и слот может "устареть" между получением списка и попыткой бронирования) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOwnerAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список интервалов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityInterval"][];
                };
            };
        };
    };
    createOwnerAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAvailabilityIntervalRequest"];
            };
        };
        responses: {
            /** @description Интервал опубликован, слоты нарезаны */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityInterval"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Интервал пересекается с уже опубликованным */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
